server:
  port: 8080
spring:
  cloud:
    config:
      server:
        grt:
          default-label: config-server
          uri: https://github.com/sergioco09/Micro-services/tree/main
          search-paths: config-data
  application:
    name: config-service