server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: /home/sergio/Documentos/Micros funcionales y colecciones/Micro-services
          search-paths: config-data
  application:
    name: config-service